# Docker-compose for LOFAR
version: '3.2'
services:
  lofar-dlg:
    image: "dlglofar/centos7"
    network_mode: "host"
    labels:
      NAME: "lofar_daliuge"
    command:
      - dlg 
      - nm 
      - -w
      - /local/workdir
      - -H 0.0.0.0
      - -l
      - /local/workdir/log/
      - -vvvv
    volumes:
      - type: bind
        source: /var/scratch/grange/EOSCdata/cal 
        target: /local/data
      - type: bind
        source: /local/grange/dlg_work
        target: /local/workdir
      - type: bind
        source: /var/scratch/grange/Daliuge/shared
        target: /local/shared
#    restart: always

